[package]
name = "slash"
version = "0.1.0"
authors = ["adumbidiot <nathaniel.daniel23@outlook.com>"]
edition = "2018"

[dependencies]
gl = "0.11"
glutin = "0.19"
nalgebra = "0.17"
image = "0.22"

[dependencies.rusttype]
version = "0.7"
features = ["gpu_cache"]